"""Initial migration

Revision ID: 149f87b4fbaa
Revises: 
Create Date: 2025-02-16 04:32:08.859280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '149f87b4fbaa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('current_latitude', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('current_longitude', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('previous_latitude', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('previous_longitude', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'previous_longitude')
    op.drop_column('students', 'previous_latitude')
    op.drop_column('students', 'current_longitude')
    op.drop_column('students', 'current_latitude')
    # ### end Alembic commands ###
