"""Initial migration

Revision ID: 387c05059f34
Revises: 1ee4f00cf73d
Create Date: 2025-03-13 21:35:21.708436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import json


# revision identifiers, used by Alembic.
revision: str = '387c05059f34'
down_revision: Union[str, None] = '1ee4f00cf73d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('reminder_status', sa.JSON(), nullable=False))

    conn = op.get_bind()
    conn.execute(
        sa.text("UPDATE attendance SET reminder_status = json('{}') WHERE reminder_status IS NULL")
    )

    #op.create_unique_constraint(None, 'student_info', ['marticno'])
    with op.batch_alter_table("student_info") as batch_op:
        batch_op.create_unique_constraint("uq_student_marticno", ['marticno'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_info', type_='unique')
    op.drop_column('attendance', 'reminder_status')
    # ### end Alembic commands ###
