"""Initial migration

Revision ID: 3eb6a89cbe9c
Revises: c2d516572b2b
Create Date: 2025-02-28 08:12:24.483449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb6a89cbe9c'
down_revision: Union[str, None] = 'c2d516572b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_bind_id', sa.String(length=36), nullable=True),
    sa.Column('venue_name', sa.String(length=100), nullable=True),
    sa.Column('venue_desc', sa.String(length=100), nullable=True),
    sa.Column('venue_address', sa.String(length=250), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_bind_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venues')
    # ### end Alembic commands ###
