"""Initail migration

Revision ID: 63aac2659165
Revises: 3eb6a89cbe9c
Create Date: 2025-03-02 20:34:18.399304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63aac2659165'
down_revision: Union[str, None] = '3eb6a89cbe9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_bind_id', sa.String(length=36), nullable=True),
    sa.Column('venue_id', sa.String(length=36), nullable=True),
    sa.Column('event_title', sa.String(length=255), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=False),
    sa.Column('event_status', sa.Enum('pending', 'started', 'done'), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.venue_bind_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_bind_id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('student_bind_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('pending', 'present', 'absent'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_bind_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    op.drop_table('events')
    # ### end Alembic commands ###
