"""Initial migration

Revision ID: c2d516572b2b
Revises: 
Create Date: 2025-02-26 07:04:26.017390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d516572b2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_bind_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('uid', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('current_latitude', sa.String(length=100), nullable=True),
    sa.Column('current_longitude', sa.String(length=100), nullable=True),
    sa.Column('previous_latitude', sa.String(length=100), nullable=True),
    sa.Column('previous_longitude', sa.String(length=100), nullable=True),
    sa.Column('last_logged_in', sa.String(), nullable=True),
    sa.Column('previous_last_logged_in', sa.String(), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_bind_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_key', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verifications_email'), 'email_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_email_verifications_email_key'), 'email_verifications', ['email_key'], unique=False)
    op.create_index(op.f('ix_email_verifications_token'), 'email_verifications', ['token'], unique=False)
    op.create_table('reset_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reset_pwd_key', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reset_verifications_email'), 'reset_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_reset_verifications_reset_pwd_key'), 'reset_verifications', ['reset_pwd_key'], unique=False)
    op.create_index(op.f('ix_reset_verifications_token'), 'reset_verifications', ['token'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_bind_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('uid', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('email_verify', sa.Enum('Verfied', 'Not Verified'), nullable=True),
    sa.Column('current_latitude', sa.String(length=100), nullable=True),
    sa.Column('current_longitude', sa.String(length=100), nullable=True),
    sa.Column('previous_latitude', sa.String(length=100), nullable=True),
    sa.Column('previous_longitude', sa.String(length=100), nullable=True),
    sa.Column('face_encoding', sa.String(), nullable=True),
    sa.Column('last_logged_in', sa.String(), nullable=True),
    sa.Column('previous_last_logged_in', sa.String(), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('student_bind_id')
    )
    op.create_table('student_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('Male', 'Female'), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('marticno', sa.String(length=15), nullable=True),
    sa.Column('dept', sa.String(length=30), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('program', sa.Enum('Degree', 'NCE'), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_bind_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dept'),
    sa.UniqueConstraint('marticno'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_info')
    op.drop_table('students')
    op.drop_index(op.f('ix_reset_verifications_token'), table_name='reset_verifications')
    op.drop_index(op.f('ix_reset_verifications_reset_pwd_key'), table_name='reset_verifications')
    op.drop_index(op.f('ix_reset_verifications_email'), table_name='reset_verifications')
    op.drop_table('reset_verifications')
    op.drop_index(op.f('ix_email_verifications_token'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_email_key'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_email'), table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_table('admins')
    # ### end Alembic commands ###
