"""Initial migration

Revision ID: c986924ca238
Revises: f977f8af7cf3
Create Date: 2025-02-19 12:04:05.342269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c986924ca238'
down_revision: Union[str, None] = 'f977f8af7cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('last_logged_in', sa.String(), nullable=True))
    op.add_column('students', sa.Column('previous_last_logged_in', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'previous_last_logged_in')
    op.drop_column('students', 'last_logged_in')
    # ### end Alembic commands ###
